# Generated by Django 2.2.15 on 2020-10-14 21:07

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20200407_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_settings',
            field=jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, help_text='JSON string containing custom backend settings.', load_kwargs={}, verbose_name='Custom settings'),
        ),
    ]
