# Generated by Django 3.2.12 on 2023-05-10 02:27

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_account_microfrontend_url_field_from_SiteConfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_settings',
            field=jsonfield.fields.JSONField(blank=True, default={}, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, help_text='JSON string containing custom backend settings.', load_kwargs={}, verbose_name='Custom settings'),
        ),
    ]
