# Generated by Django 3.2.25 on 2025-12-01 16:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_account_microfrontend_url_field_from_SiteConfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_settings',
            field=jsonfield.fields.JSONField(blank=True, default={}, help_text='JSON string containing custom backend settings.', verbose_name='Custom settings'),
        ),
    ]
