name: Tutor Build Action Test

on:
  push:
    branches:
      - 'vue/PADV-325.tests'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD-HH-mm
      - name: Build Image
        uses: Pearson-Advance/tutor-build-image-action@0.2.0
        with:
          python-version: ${{ vars.BUILD_PYTHON_VERSION }}
          tutor-version: ${{ vars.BUILD_TUTOR_VERSION }}
          path-image-to-be-built: 'env/plugins/ecommerce/build/ecommerce'
          repository-name: ${{ vars.BUILD_MAIN_REPOSITORY_NAME }}
          image-name: ${{ vars.BUILD_MAIN_IMAGE_NAME }}
          image-tag: ${{ vars.ECOMMERCE_TUTOR_PLUGIN_VERSION }}-${{ steps.current-time.outputs.formattedTime }}
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
          use-docker-cache: ${{ vars.BUILD_USE_CACHE }}
          tutor-plugin-sources: '("git+https://github.com/overhangio/tutor-ecommerce.git@v${{ vars.ECOMMERCE_TUTOR_PLUGIN_VERSION }}" "git+https://github.com/overhangio/tutor-mfe.git@v15.0.5" "git+https://github.com/overhangio/tutor-discovery.git@v15.0.0")'
          tutor-plugin-names: '("ecommerce" "discovery" "mfe")'
